config/routes.rb
Rails.application.routes.draw do
  get 'dislikes/list'
  get 'likes/list'
  put "follows/follow/:id" => "follows#follow", :as => 'follows_follow'
  put "follows/cancel/:id" => "follows#cancel", :as => 'follows_cancel'
  put "likes/add/:id" => "likes#add", :as => 'likes_add'
  put "likes/cancel/:id" => "likes#cancel", :as => 'likes_cancel'
  put "dislikes/add/:id" => "dislikes#add", :as => 'dislikes_add'
  put "dislikes/cancel/:id" => "dislikes#cancel", :as => 'dislikes_cancel'
  # resources :follows
  devise_for :users
  get "tweets", :to => "tweets#index", :as => :user_root
  get "users/show"

  resources :users do
    resources :follows
  end
  resources :users do
    resources :likes
  end
  resources :users do
    resources :dislikes
  end
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root :to => "tweets#index"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :users, :through => :likes
    has_many :dislikes, dependent: :destroy
    has_many :users, :through => :dislikes
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.order(id: :DESC)
    @tweet = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_path, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :content, :like, :unlike)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet != nil %>
    <% if tweet.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

        <ul>
          <% tweet.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

<!--
  <div>
    User ID
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>
-->

  <div class="tweet_text_area">
    <!-- Tweet -->
    <!-- <%= form.label :content, style: "display: block" %> -->
    <%= form.text_area :content, size:"36x7" %>
  </div>

  <!-- <div>
    Like
    <%= form.label :like, style: "display: block" %>
    <%= form.number_field :like %>
  </div> -->

  <!-- <div>
    Unlike 
    <%= form.label :unlike, style: "display: block" %>
    <%= form.number_field :unlike %>
  </div>-->

  <div class="tweet_btn">
    <%= form.submit(t("tweet"), class: "btn btn-primary") %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <div class="flex">
      <% if tweet.user_id != nil %>
        <% begin %>
          <!-- <div data-toggle="popover" title='<%= link_to(User.find(tweet.user_id).user_name, User.find(tweet.user_id)) %>' data-bs-html="true" data-bs-content="<strong>hoge</strong>"> -->
          <div class="linkbox">
              <%= link_to("", User.find(tweet.user_id)) %>
                <span class="profile_screen_name"><%= User.find(tweet.user_id).screen_name %></span>
                <span class="profile_user_name"> @<%= User.find(tweet.user_id).user_name %></span>                
          </div>
          <!-- @userid -->
          <div class="separator">-</div>
          <%= tweet.created_at.to_s(:datetime_jp)%>
        <% rescue %>
          <div data-toggle="popover" title='' data-bs-html="true" data-bs-content="">
                <span class="profile_screen_name"></span>
                <span class="profile_user_name"></span>                
          </div>
          <!-- @userid -->
          <div class="separator">-</div>
          <%= tweet.created_at.to_s(:datetime_jp)%>
        <% end %>
      <% end %>
    </div>
  </p>

  <p>
    <strong>Content:</strong>
    <%= tweet.content %>
  </p>

  <p>
    <div class="reaction">
      <% @likes = Like.all %>
      <% if Dislike.where(user_id: current_user.id, tweet_id: tweet.id).exists? %>
        <button class="btn btn-outline-danger btn-sm text-black" disabled>👍 <%= Like.where(tweet_id: tweet.id).count.to_s %></button>
      <% else %>      
        <% if Like.where(user_id: current_user.id, tweet_id: tweet.id).exists? %>
        <% like = Like.where(user_id: current_user.id, tweet_id: tweet.id)[0] %>
          <%= form_tag "/likes/cancel/"+like.id.to_s, :method => 'put' do %>
            <%= submit_tag "👍 "+Like.where(tweet_id: tweet.id).count.to_s, :name => "Cancel", class:"btn btn-danger btn-sm" %>
          <% end %>
        <% else %>
          <%= form_tag "/likes/add/"+tweet.id.to_s, :method => 'put' do %>
            <%= submit_tag "👍 "+Like.where(tweet_id: tweet.id).count.to_s, :name => "Add", class:"btn btn-outline-danger btn-sm text-black" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="reaction">
      <% @dislikes = Dislike.all %>
      <% if Like.where(user_id: current_user.id, tweet_id: tweet.id).exists? %>
        <button class="btn btn-outline-secondary btn-sm" disabled>👎 <%= Dislike.where(tweet_id: tweet.id).count.to_s %></button>
      <% else %>      
        <% if Dislike.where(user_id: current_user.id, tweet_id: tweet.id).exists? %>
        <% dislike = Dislike.where(user_id: current_user.id, tweet_id: tweet.id)[0] %>
          <%= form_tag "/dislikes/cancel/"+dislike.id.to_s, :method => 'put' do %>
            <%= submit_tag "👎 "+Dislike.where(tweet_id: tweet.id).count.to_s, :name => "Cancel", class:"btn btn-secondary btn-sm" %>
          <% end %>
        <% else %>
          <%= form_tag "/dislikes/add/"+tweet.id.to_s, :method => 'put' do %>
            <%= submit_tag "👎 "+Dislike.where(tweet_id: tweet.id).count.to_s, :name => "Add", class:"btn btn-outline-secondary btn-sm" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </p>
  <div class="clear"></div>
</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<!-- <p style="color: green"><%= notice %></p> -->

<div id="right_scroll">
  <h1 id="tweets" style="margin-left: 10px;">Tweets</h1>
  <table class="table table-striped">
    <div>
      <tbody>
        <% @tweets.each do |tweet| %>
          <tr>
            <td class="table-info"></td>
            <td class="table-info">
              <div class="content">
                <%= render tweet %>
                <p>
                  <% if current_user.id == tweet.user_id || current_user.id == 1 %>
                  <!-- <%= link_to "Show this tweet", tweet %> -->
                  <%= button_to t("delete"), tweet, method: :delete, data: {turbo_confirm: "Are you sure?"}, class: "btn btn-danger btn-sm" %>
                  <% end %>
                </p>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </div>
  </table>

  <!-- <%= link_to "New tweet", new_tweet_path %> -->
</div>

app/views/tweets/new.html.erb
<%= render "form", tweet: @tweet %>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet), class: "text-white" %> |
  <%= link_to "Back to tweets", tweets_path, class: "text-white" %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-sm" %>
</div>