config/routes.rb
Rails.application.routes.draw do
  get 'dislikes/list'
  get 'likes/list'
  put "follows/follow/:id" => "follows#follow", :as => 'follows_follow'
  put "follows/cancel/:id" => "follows#cancel", :as => 'follows_cancel'
  put "likes/add/:id" => "likes#add", :as => 'likes_add'
  put "likes/cancel/:id" => "likes#cancel", :as => 'likes_cancel'
  put "dislikes/add/:id" => "dislikes#add", :as => 'dislikes_add'
  put "dislikes/cancel/:id" => "dislikes#cancel", :as => 'dislikes_cancel'
  # resources :follows
  devise_for :users
  get "tweets", :to => "tweets#index", :as => :user_root
  get "users/show"

  resources :users do
    resources :follows
  end
  resources :users do
    resources :likes
  end
  resources :users do
    resources :dislikes
  end
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root :to => "tweets#index"
end

app/views/shared/_footer.html.erb
Copyright (C) 2022-2023, Masaki Saito

app/views/shared/_menu_bar.html.erb
<% tweet_items = [
    { :link => tweets_path, :name => (t 'Twitter2') },
    { :link => "#page_top", :name => (t 'back_to_top') },
    #{ :link => new_tweet_path, :name => (t 'new_memo') },
    #{ :link => find_tweets_path, :name => 'Find Memos' },
    #{ :link => follows_list_path, :name => 'Follow List' },
    #{ :link => find_friends_path, :name => 'Find Friends' },
    { :link => 'https://twitter.com', :name => 'Original Twitter' },
    { :link => '', :name => 'About This Page', :disabled => true }
    ] -%>

<!-- Navigation-->
<nav class="navbar navbar-light bg-light static-top">
    <div class="container">
        <b><%= link_to((t 'Twitter2'), tweets_path, class: "navbar-brand") %></b>
        <!-- <a class="btn btn-primary" href="#signup">Sign Up</a> -->
        <% if current_user != nil %>
            <div class="linkbox">
                <%= link_to("", User.find(current_user.id)) %>
                <span class="profile_screen_name"><%= current_user.screen_name %></span>
                <span class="profile_user_name">@<%= current_user.user_name %></span>
            </div>
            <span class="config_profile"><%= link_to('Sign out', destroy_user_session_path, :method => :delete, data:{turbo_method: :delete}) %></span>
            <span class="config_profile"><%= link_to('Edit your info', edit_user_path(:id => current_user.id)) %></span>
            <span class="config_profile"><%= link_to 'Change Password', edit_user_registration_path %></span>
        <% end %>
    </div>
</nav>
<!--
<div id="menu_bar">
    <% tweet_items.each_with_index do | item, index | -%>
        <% if index > 0 %> &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<% end -%>
        <%= menu_link_to item -%>
    <% end -%>
</div>
-->

app/views/shared/_tweet_post_bar.html.erb
<% if current_user %>
<div class="current_user">
    <div class="linkbox">
        <%= link_to("", User.find(current_user.id)) %>
        <span class="profile_screen_name"><%= current_user.screen_name %></span><br />
        <span class="profile_user_name">@<%= current_user.user_name %></span><br />
    </div>
</div>
<div style="margin-left: 10px; text-align: center;">
    <div class="row">
        <div class="col"><a href="<%= root_url+"users/"+current_user.id.to_s %>/follows">Follows</a></div>
        <div class="col"><a href="<%= root_url+"users/"+current_user.id.to_s %>/follows">Followers</a></div>
        <div class="col">Tweets</div>
    </div>
    <div class="row">
        <div class="col"><%= Follow.where(user_id: current_user.id).count %></div>
        <div class="col"><%= Follow.where(follow_user_id: current_user.id).count %></div>
        <div class="col"><%= Tweet.where(user_id: current_user.id).count %></div>
    </div>
</div>
<!--
<div>
    <span class="config_profile"><%= link_to('Sign out', destroy_user_session_path, :method => :delete, data:{turbo_method: :delete}) %></span>
    <span class="config_profile"><%= link_to('Edit your info', edit_user_path(:id => current_user.id)) %></span>
    <span class="config_profile"><%= link_to 'Change Password', edit_user_registration_path %></span>
</div>
-->
<% end %>

<div class="new_tweet">
    <%= render template: new_tweet_path %>
</div>