config/routes.rb
Rails.application.routes.draw do
  get 'dislikes/list'
  get 'likes/list'
  put "follows/follow/:id" => "follows#follow", :as => 'follows_follow'
  put "follows/cancel/:id" => "follows#cancel", :as => 'follows_cancel'
  put "likes/add/:id" => "likes#add", :as => 'likes_add'
  put "likes/cancel/:id" => "likes#cancel", :as => 'likes_cancel'
  put "dislikes/add/:id" => "dislikes#add", :as => 'dislikes_add'
  put "dislikes/cancel/:id" => "dislikes#cancel", :as => 'dislikes_cancel'
  # resources :follows
  devise_for :users
  get "tweets", :to => "tweets#index", :as => :user_root
  get "users/show"

  resources :users do
    resources :follows
  end
  resources :users do
    resources :likes
  end
  resources :users do
    resources :dislikes
  end
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root :to => "tweets#index"
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :user
    def new_follow(u_id, f_u_id)
        @follow = Follow.new(user_id: u_id, follow_user_id: f_u_id)
    end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  # before_action :set_follow, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # def list
  #   @users = User.all
  #   @users -= [current_user]
  # end


  # put /follows/follow
  # put /follows/follow.json
  def follow
    follow_params = {
      :follow_user_id => params[:id],
      :user_id => current_user.id
    }
    @follow = Follow.new( follow_params )

    respond_to do |format|
      if @follow.save
        format.html { redirect_to user_path(params["id"]) }
        format.json { render :json => @follow  }
      else
        format.html { render action: "list", :alert => 'Failed to follow.' }
        format.json { render json: @follow.errors }
      end
    end
  end

  # put /follows/cancel
  # put /follows/cancel.json
  def cancel
    @follow = Follow.find_by_id( params[:id] )
    @follow.destroy
    redirect_to user_path(params["id"])
  end

  # GET /follows or /follows.json
  def index
    @follows = Follow.all
    @users = User.all
    @users -= [current_user]
    @follows = Follow.where(user_id: current_user.id)
  end

  # GET /follows/1 or /follows/1.json
  def show
  end

  # GET /follows/new
  def new
    @follow = Follow.new
  end

  # GET /follows/1/edit
  def edit
  end

  # POST /follows or /follows.json
  def create
    @follow = Follow.new(follow_params)

    respond_to do |format|
      if @follow.save
        format.html { redirect_to follow_url(@follow), notice: "Follow was successfully created." }
        format.json { render :show, status: :created, location: @follow }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /follows/1 or /follows/1.json
  def update
    respond_to do |format|
      if @follow.update(follow_params)
        format.html { redirect_to follow_url(@follow), notice: "Follow was successfully updated." }
        format.json { render :show, status: :ok, location: @follow }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follows/1 or /follows/1.json
  def destroy
    @follow.destroy

    respond_to do |format|
      format.html { redirect_to follows_url, notice: "Follow was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follow
      @follow = Follow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def follow_params
      params.require(:follow).permit(:user_id, :follow_user_id)
    end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_follow.html.erb
<div id="<%= dom_id follow %>">
<!-- 
  <p>
    <strong>User:</strong>
    <%= follow.user_id %>
  </p>
 -->

  <p>
    <%= render template: "users/show" %>
  </p>

</div>

app/views/follows/_form.html.erb
<%= form_with(model: follow) do |form| %>
  <% if follow.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(follow.errors.count, "error") %> prohibited this follow from being saved:</h2>

      <ul>
        <% follow.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :follow_user_id, style: "display: block" %>
    <%= form.number_field :follow_user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing follow</h1>

<%= render "form", follow: @follow %>

<br>

<div>
  <%= link_to "Show this follow", @follow %> |
  <%= link_to "Back to follows", follows_path %>
</div>

app/views/follows/index.html.erb
<p style="color: green"><%= notice %></p>

    <h1><%= User.find(params[:user_id]).screen_name %></h1>
<div class="row">
  <div class="col">
    <div id="follows">
      <h2>Follows</h2>
      <hr />
      <% @follows = Follow.all%>
      <% @tmp_f = @follow %>
      <% @follows.each do |follow| %>
        <% @follow = [follow] %>
        <% if params[:user_id].to_i == follow.user_id %>
          <% @user = User.find(follow.follow_user_id) %>
          <%= render @user %>
          <hr />
        <% end %>
        <p>
        </p>
      <% end %>
      <% @follow = @tmp_f %>
    </div>
  </div>

  <div class="col">
    <div id="follows">
      <h2>Followers</h2>
      <hr />
      <% @tmp_f = @follow %>
      <% @follows.each do |follow| %>
        <% @follow = [follow] %>
        <% if params[:user_id].to_i == follow.follow_user_id %>
          <% @user = User.find(follow.user_id) %>
          <%= render @user %>
          <hr />
        <% end %>
        <p>
        </p>
      <% end %>
      <% @follow = @tmp_f %>
    </div>
  </div>
</div>

app/views/follows/new.html.erb
<h1>New follow</h1>

<%= render "form", follow: @follow %>

<br>

<div>
  <%= link_to "Back to follows", follows_path %>
</div>

app/views/follows/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @follow %>

<div>
  <%= link_to "Edit this follow", edit_follow_path(@follow) %> |
  <%= link_to "Back to follows", follows_path %>

  <%= button_to "Destroy this follow", @follow, method: :delete %>
</div>